version: '3.9'

services:
  backend:
    build: .
    container_name: ipa-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # ważne: ignoruj lokalny node_modules
    env_file:
      - .env
    command: npm run dev
